# Generated by Django 3.1.4 on 2023-01-01 16:42

from django.db import migrations, models
import mylib.image


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mylib.image.scramble, verbose_name='Profile Image'),
        ),
    ]
