# Generated by Django 3.1.4 on 2022-03-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20220228_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='schedule',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='time_slot',
            field=models.ManyToManyField(to='clinic.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sartuday', 'Sartuday'), ('Holiday', 'Holiday')], max_length=10, verbose_name='Day'),
        ),
    ]
