# Generated by Django 3.1.4 on 2023-01-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_timeslot_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_invites',
            field=models.ManyToManyField(to='clinic.Clinic'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Amount'),
        ),
    ]
