# Generated by Django 3.2.18 on 2023-03-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciality",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
    ]
